---
repository: "git-cherry-picker"
organization: "locusview"
gitUserName: "nortecview"
gitUserEmail: "build@locusview.com"
gitUserPass: "9V2eQStZuIAV2msYEaE_3rOw3LXJ6Si--APpDO3rYthCZUOEufaa4AgKztdSGyb4"
gmailUser: "nortecview.jenkins@gmail.com"
gmailPass: "bIfWQ7zZMsqjWNRyqwEQow"
approverTokens:
