---
repository: "git-cherry-picker"
organization: "locusview"
gitUserName: "nortecview"
gitUserEmail: "build@locusview.com"
gitUserPass: "YOBxBrVUczXqs6Scmf5aiw"
gmailUser: "nortecview.jenkins@gmail.com"
gmailPass: "bIfWQ7zZMsqjWNRyqwEQow"
approverTokens:
- "PukMsPF7rC1hmK5vSxwnWunbaHpQPXvgEssIQvJErMt_1Ybk8-LoJwgKztdSGyb4"
